import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import Providers from "@/provider/Providers";
import StoreProvider from "@/store/StoreProvider";


export const metadata: Metadata = {
  title: "숙박예약 앱",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      {/* react-query를 이용하기 위해 묶어줌 context와 같은 개념 */}     
        <body>
          <StoreProvider>
            <Header></Header>
            <div className='mx-auto max-w-[768px] w-[100%]'>
              {children}
            </div>
          </StoreProvider>
        </body>
    </html>
  );
}
